services:
  payment-service-app:
    image: payment-service-app
    ports:
    - "8080:8080"
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment_db
      LC_MESSAGE: en_US.UTF-8
    volumes:
    - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  pgdata: